# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: eurAIka
email: euraika.sciences@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An AI powered research platform designed to accelerate every phase of the scientific discovery process.
url: "https://euraika-sciences.github.io"  
#baseurl: "euraika-sciences" # the subpath of your site, e.g. /blog
baseurl: ""

#url: "https://euraika-sciences.github.io" # the base hostname & protocol for your site, e.g. http://example.com
mastodon_username: 
github_username:  euraika-sciences

# Permalink to index page
permalink: /index/

# Sidebar entries
menu:
  - title: The Whiteboard
    url:   /the-whiteboard/
  - title: The Librarian
    url:   /the-librarian/    
  - title: The Code
    url:   /the-coder/
  - title: About
    url:   /about/
  - title: FAQ
    url:   /faq/
    
# Build settings
#theme: minima
#theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
